version: "3"

services:
  db-posgres:
    image: postgres
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    ports:
      - "5433:5432"
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/backend
      - staticfiles:/backend/staticfiles
    environment:
      - CHANNELS_REDIS_HOST=db-redis
      - CHANNELS_REDIS_PORT=6379

      - POSTGRES_HOST=db-posgres
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_PORT=5432
    command: >
      sh -c 
      "python manage.py collectstatic --no-input && 
      python manage.py makemigrations && 
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0 -p 8000 backend.wsgi:application"
    depends_on:
      - db-posgres

  nginx:
    image: nginx:1-alpine3.17
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/etc/nginx/logs
      - staticfiles:/backend/staticfiles/
    ports:
      - "80:80"
    depends_on:
      - backend

  backend-java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/backend/src/
    command: >
      sh -c 
      "mvn install && 
      java -jar /backend/target/chat-0.0.1-SNAPSHOT.jar"

  backend-java-message:
    build:
      context: ./message
      dockerfile: Dockerfile
    volumes:
      - ./message/src/:/backend/src/
    command: >
      sh -c 
      "mvn install && 
      java -jar /backend/target/chat-0.0.1-SNAPSHOT.jar"


volumes:
  staticfiles: