// Code generated by goro;

package cookieservice

// This file was generated by the goro tool.

import (
	"Cookie/internal/entity"
	"Cookie/internal/service"
	"context"
)

type cookieRepo interface {
	service.Transactor
	Save(ctx context.Context, cookie entity.CookieResponse) error
	GetAll(ctx context.Context) ([]entity.CookieResponse, error)
}

type Service struct {
	cookieRepo cookieRepo
}

func NewService(cookieRepo cookieRepo) *Service {
	return &Service{
		cookieRepo: cookieRepo,
	}
}
