// Code generated by goro; DO NOT EDIT.

package app

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

import (
	"github.com/jmoiron/sqlx"

	"Cookie/internal/usecase"

	"Cookie/internal/service/cookieservice"

	"Cookie/internal/adapter/pgsqlxrepo/cookierepo"
)

type Container struct {
	pgsqlx *sqlx.DB

	deps map[string]interface{}
}

func NewContainer(pgSqlxConn *sqlx.DB) *Container {

	return &Container{
		pgsqlx: pgSqlxConn,

		deps: make(map[string]interface{}),
	}
}

func (c *Container) GetUseCase() *usecase.UseCase {

	return usecase.NewUseCase(c.getCookieService())
}

func (c *Container) getPgsqlx() *sqlx.DB {
	return c.pgsqlx
}

func (c *Container) getCookieService() *cookieservice.Service {

	return cookieservice.NewService(c.getCookieRepo())
}

func (c *Container) getCookieRepo() *cookierepo.Repository {

	return cookierepo.NewRepository(c.getPgsqlx())
}
